# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 01:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arquivo',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Arquivo',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
