# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 01:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171206_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=150)),
                ('status', models.IntegerField(choices=[(1, 'Impresso'), (2, 'Aguardando aprovação'), (3, 'Impressão negada')], default=2)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Usuario')),
            ],
        ),
    ]
