# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='nome',
            field=models.CharField(default='teste', max_length=100),
            preserve_default=False,
        ),
    ]
