# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-23 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_arquivo_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='copias',
            field=models.IntegerField(default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='arquivo',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
