# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-23 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20181023_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='cor',
            field=models.IntegerField(choices=[(1, 'Colorido'), (0, 'Preto e branco')], default=0),
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='copias',
            field=models.IntegerField(default=1),
        ),
    ]
